// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4kzmHy_LEfNfdvrEpSPeV7_rvFTdLieM',
    appId: '1:955661553684:android:146f34ae979ca7ba3c1701',
    messagingSenderId: '955661553684',
    projectId: 'firstday-e5e57',
    databaseURL: 'https://firstday-e5e57-default-rtdb.firebaseio.com',
    storageBucket: 'firstday-e5e57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn5i_S_Qb0nYfvqhuLuyGvXMxHTQUHnPM',
    appId: '1:955661553684:ios:597b51cd1b081bc93c1701',
    messagingSenderId: '955661553684',
    projectId: 'firstday-e5e57',
    databaseURL: 'https://firstday-e5e57-default-rtdb.firebaseio.com',
    storageBucket: 'firstday-e5e57.appspot.com',
    iosClientId: '955661553684-iqmrv77jksm14o0hkkfmbq20i9m1esuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstday',
  );
}
